# Generated by Django 2.1.3 on 2020-01-22 04:36

import api_basebone.core.fields
from django.db import migrations, models
import django.db.models.deletion
import trigger_core.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trigger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(default=trigger_core.models.UUID, unique=True, verbose_name='标识')),
                ('name', models.CharField(default='', max_length=50, verbose_name='名称')),
                ('summary', models.TextField(default='', verbose_name='api说明')),
                ('event', models.CharField(choices=[('before_create', '创建前'), ('after_create', '创建后'), ('before_update', '更新前'), ('after_update', '更新后'), ('before_delete', '删除前'), ('after_delete', '删除后')], max_length=20, verbose_name='操作')),
                ('disable', models.BooleanField(default=False, verbose_name='停用')),
            ],
            options={
                'verbose_name': '触发器',
                'verbose_name_plural': '触发器',
            },
        ),
        migrations.CreateModel(
            name='TriggerAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', '创建记录'), ('update', '更新记录'), ('delete', '删除记录')], max_length=20, verbose_name='条件类型')),
                ('app', models.CharField(default='', max_length=50, verbose_name='app名字')),
                ('model', models.CharField(default='', max_length=50, verbose_name='数据模型名字')),
                ('fields', api_basebone.core.fields.JSONField(blank=True, default={}, verbose_name='操作的属性')),
                ('filters', api_basebone.core.fields.JSONField(blank=True, default=[], verbose_name='操作的条件')),
                ('trigger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trigger_core.Trigger', verbose_name='trigger')),
            ],
            options={
                'verbose_name': '触发器行为',
                'verbose_name_plural': '触发器行为',
            },
        ),
        migrations.CreateModel(
            name='TriggerCondition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=50, null=True, verbose_name='app名字')),
                ('model', models.CharField(max_length=50, null=True, verbose_name='数据模型名字')),
                ('filters', api_basebone.core.fields.JSONField(blank=True, default=[], verbose_name='筛选条件')),
                ('trigger', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='trigger_core.Trigger', verbose_name='trigger_condition')),
            ],
            options={
                'verbose_name': '触发器条件',
                'verbose_name_plural': '触发器条件',
            },
        ),
        migrations.AlterIndexTogether(
            name='triggercondition',
            index_together={('app', 'model')},
        ),
    ]
