# Generated by Django 2.2.9 on 2020-02-03 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trigger_core', '0002_auto_20200203_2333'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trigger',
            old_name='condition',
            new_name='triggercondition',
        ),
    ]
