# Generated by Django 2.2.9 on 2020-02-04 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trigger_core', '0003_auto_20200203_2348'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trigger',
            old_name='triggercondition',
            new_name='condition',
        ),
    ]
