# Generated by Django 2.2.9 on 2020-08-03 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trigger_core', '0006_auto_20200724_2307'),
    ]

    operations = [
        migrations.AddField(
            model_name='triggeraction',
            name='mime_type',
            field=models.CharField(choices=[['plain', '纯文本'], ['html', '富文本']], default='plain', max_length=20, verbose_name='格式'),
        ),
    ]
