# Generated by Django 2.2.9 on 2020-11-19 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trigger_core', '0007_triggeraction_mime_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='triggeraction',
            old_name='text_template',
            new_name='content_template',
        ),
        migrations.RenameField(
            model_name='triggeraction',
            old_name='mime_type',
            new_name='email_mime_type',
        ),
        migrations.RenameField(
            model_name='triggeraction',
            old_name='subject_template',
            new_name='title_template',
        ),
        migrations.AddField(
            model_name='triggeraction',
            name='email_enabled',
            field=models.BooleanField(default=False, verbose_name='启用邮件通知'),
        ),
        migrations.AlterField(
            model_name='triggeraction',
            name='action',
            field=models.CharField(choices=[('create', '创建记录'), ('update', '更新记录'), ('delete', '删除记录'), ('notify', '发送通知')], max_length=20, verbose_name='条件类型'),
        ),
    ]
