# Generated by Django 2.2.17 on 2021-01-27 18:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import trigger_core.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trigger_core', '0009_auto_20201123_0813'),
    ]

    operations = [
        migrations.AddField(
            model_name='trigger',
            name='create_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AddField(
            model_name='trigger',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间'),
        ),
        migrations.AddField(
            model_name='triggeraction',
            name='create_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AddField(
            model_name='triggeraction',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间'),
        ),
        migrations.AddField(
            model_name='triggeraction',
            name='script',
            field=models.TextField(null=True, verbose_name='脚本'),
        ),
        migrations.AddField(
            model_name='triggeraction',
            name='slug',
            field=models.SlugField(default=trigger_core.models.UUID, unique=True, verbose_name='标识'),
        ),
        migrations.AlterField(
            model_name='triggeraction',
            name='action',
            field=models.CharField(choices=[('create', '创建记录'), ('update', '更新记录'), ('delete', '删除记录'), ('notify', '发送通知')], max_length=20, verbose_name='响应'),
        ),
        migrations.AlterField(
            model_name='triggeraction',
            name='app',
            field=models.CharField(default='', max_length=50, verbose_name='app名称'),
        ),
        migrations.AlterField(
            model_name='triggeraction',
            name='model',
            field=models.CharField(default='', max_length=50, verbose_name='模型名称'),
        ),
    ]
