# Generated by Django 2.2.17 on 2021-01-31 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trigger_core', '0011_triggeraction_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='triggeraction',
            name='action',
            field=models.CharField(choices=[('create', '创建记录'), ('update', '更新记录'), ('delete', '删除记录'), ('notify', '发送通知'), ('script', '执行脚本')], max_length=20, verbose_name='响应'),
        ),
    ]
